### PR TITLE
TASK: Update binary to the lastest version

### PR DESCRIPTION
**Pull request by markusguenther**
The binary has not been updated for 14 months, so the package is not usable via composer.

### CODE REVIEW

**Comment by cvette** [comment]
The phar binary is, and should not be committed. If you install it via composer you can run ./bin/neoscs directly, or am I missing something? I'll create an action that builds the phar for each release.

**Comment by markusguenther** [comment]
Hmm then I maybe missed something, got this error and with the compiled phar it works... 🤷‍♂️

```
php Packages/neos-code-style/bin/neoscs.phar -c fusionLinterConfig.yaml DistributionPackages
PHP Fatal error:  Type of Vette\Neos\CodeStyle\Rules\Neos\ContextInFirstLevelRule::$tokenTypes must not be defined (as in class Vette\Neos\CodeStyle\Rules\Rule) in phar:///Volumes/Development/.../Packages/neos-code-style/bin/neoscs.phar/src/Rules/Neos/ContextInFirstLevelRule.php on line 40

Fatal error: Type of Vette\Neos\CodeStyle\Rules\Neos\ContextInFirstLevelRule::$tokenTypes must not be defined (as in class Vette\Neos\CodeStyle\Rules\Rule) in phar:///Volumes/Development/.../Packages/neos-code-style/bin/neoscs.phar/src/Rules/Neos/ContextInFirstLevelRule.php on line 40
make: *** [fusion_linter] Error 255
```

**Comment by cvette** [comment]
Your are running `php Packages/neos-code-style/bin/neoscs.phar -c fusionLinterConfig.yaml DistributionPackages`

Try this:
`php Packages/neos-code-style/bin/neoscs -c fusionLinterConfig.yaml DistributionPackages`

Even this should work:
`./Packages/neos-code-style/bin/neoscs -c fusionLinterConfig.yaml DistributionPackages`

**Comment by markusguenther** [comment]
Thanks for the quick responses.
The command works without config file parameter, but with the parameter, the rules cannot be found.

Even if I copy the config from https://raw.githubusercontent.com/cvette/neos-code-style/main/src/config.yaml
Screenshot 2022-05-17 at 10 26 46

**Comment by markusguenther** [comment]
Use it now via composer and it works fine 💙

**Pull request closed without merging**
